language: go

go:
    - 1.6
    - tip

addons:
    apt:
        packages:
        - libi2c-dev

script:
    - curl https://raw.githubusercontent.com/dasfoo/travis/master/go.sh | sh

branches:
    only:
        - master
